name: Build and Publish DITA PDF

on:
  push:
    branches:
      - revision1

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Download DITA-OT
      run: |
        wget https://github.com/dita-ot/dita-ot/releases/download/4.3.1/dita-ot-4.3.1.zip
        unzip dita-ot-4.3.1.zip

    - name: Build PDF
      run: |
        ./dita-ot-4.3.1/bin/dita \
        -i maps/manual.ditamap \
        -f pdf \
        -o published/pdf \
        --args.css=Rob/oxygen-print.css \
        --args.csspath=Rob \
        --generate.toc=toc,figure,table \
        --args.chapter.layout=BASIC \
        --args.bookmap-order=frontmatter,toc,chapter,appendix,backmatter \
        --force-page-count=auto

    - name: Commit PDF Output
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        git add published/pdf

        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Auto publish PDF output"
          git push origin revision1
        fi
