name: Build and Publish DITA

on:
  push:
    branches:
      - revision1

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'

    - name: Download DITA-OT
      run: |
        wget https://github.com/dita-ot/dita-ot/releases/download/4.3.1/dita-ot-4.3.1.zip
        unzip dita-ot-4.3.1.zip

    - name: Build HTML
      run: |
        ./dita-ot-4.3.1/bin/dita \
        -i "Manual repo/maps/manual.ditamap" \
        -f html5 \
        -o published/html

    - name: Commit Output
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

        git checkout revision1

        git add published/html

        git diff --cached --quiet || git commit -m "Auto publish HTML output"

        git push origin revision1
